### ISSUE TITLE
vitepress doesn't pick onMount from .md files

### ISSUE THREAD

**Issue by maxwowpow** [pipwerks/pdfobject-vue#1]
## description

in `.vitepress/theme/index.js`

```
import DefaultTheme from 'vitepress/theme'
import PdfObject from 'pdfobject-vue';

export default {
    ...DefaultTheme,
    enhanceApp({ app }) {
        app.component('PdfObject', PdfObject);
    }
}
```

the component per ce is recognized but something with imported modules is missing?

```
[Vue warn]: Component is missing template or render function. 
  at <PdfObject url="https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf" > 
  at <Pages/x.md onVnodeMounted=fn<runCbs> onVnodeUpdated=fn<runCbs> onVnodeUnmounted=fn<runCbs> > 
...
```

**It works** if I use the `PdfObject.vue` directly (copied from `/src/components/PdfObject.vue`)

```
import PdfObject from './components/PdfObject.vue';
```

## Repro (rough)

`npx vitepress init`

Create
`.vitepress/theme/index.js`
with the content above.

`npm i pdfobject-vue`

add 
`<pdf-object url="https://www.adobe.com/support/products/enterprise/knowledgecenter/media/c4611_sample_explain.pdf" />`
to
`./src/index.md`

`npm run dev`

Any chance you can take a look? Thanks!

**Comment by pipwerks** [comment]
I will check it out, thanks for reporting

**Comment by pipwerks** [comment]
I was able to reproduce your issue. If you change `app.component('PdfObject', PdfObject);` to `app.use(PDFObjectPlugin);` the PDF will load. (Don't forget to `npm install pdfobject`).

Side note: The PDF you were pointing to in your example won't load due to security configuration on Adobe's site. I used https://pdfobject.com/pdf/sample.pdf as my test PDF.

**Comment by maxwowpow** [comment]
Works great. Thank you!
